raizexemplo/exemplo/contatos/urls.py
from django.urls import path
from contatos import views

app_name = "contatos"

urlpatterns = [
    path('lista/', views.ContatoListView.as_view(),
    name='lista-contatos'),
    path('', views.ContatoListView.as_view(),
    name='home-contatos'),
    path('cria/', views.ContatoCreateView.as_view(),
    name='cria-contato'),
    path('atualiza/<int:pk>/', views.ContatoUpdateView.as_view(),
    name='atualiza-contato'),
    path('apaga/<int:pk>/', views.ContatoDeleteView.as_view(),
     name='apaga-contato'),
]

raizexemplo/exemplo/exemplo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('contatos/', include('contatos.urls')), # Ele procura o restante da url em contatos/urls.py
]

raizexemplo/exemplo/contatos/models.py
from django.db import models

# Create your models here.
class Pessoa(models.Model):
    id = models.AutoField(primary_key=True) # Incrementa automaticamente
    nome = models.CharField(
        max_length=100, help_text='Entre o nome') # Help_text para ajudar o usuário em formulários
    idade = models.IntegerField(help_text='Entre a idade')
    salario = models.DecimalField(
        help_text='Entre o salário',
        decimal_places=2, max_digits=8)
    email = models.EmailField(
        help_text='Informe o email', max_length=254)
    telefone = models.CharField(
        help_text='Telefone com DDD e DDI', max_length=20)
    dtNasc = models.DateField(
        help_text='Nascimento no formato DD/MM/AAAA',
        verbose_name='Data de nascimento') # Verbose_name para mudar o nome do campo em formulários (por default é o nome da variável)

    def __str__(self): # O que será mostrando quando fizer print do objeto
        return self.nome

raizexemplo/exemplo/contatos/forms.py
from django import forms
from contatos.models import Pessoa

class ContatoModel2Form(forms.ModelForm):
    dtNasc = forms.DateField(
        input_formats=['%d/%m/%Y'],
        label='Data do nascimento',
        help_text='Nascimento no formato DD/MM/AAAA',
    )

    class Meta:
        model = Pessoa
        fields = '__all__'

raizexemplo/exemplo/contatos/views.py
from django.shortcuts import render, get_object_or_404
from contatos.models import Pessoa
from django.views.generic.base import View
from contatos.forms import ContatoModel2Form
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse_lazy

# Create your views here.

class ContatoListView(View):
    def get(self, request, *args, **kwargs):
        pessoas = Pessoa.objects.all().order_by('nome')
        
        contexto = { 'pessoas': pessoas } # Dicionário que será passado para o template
        # Valor da chave é o objeto com todas as pessoas
        
        return render(
            request,
            'contatos/listaContatos.html',
            contexto
        )

class ContatoCreateView(View):
    def get(self, request, *args, **kwargs):
        contexto = { 'formulario': ContatoModel2Form, }
        return render(request, "contatos/criaContato.html", contexto)

    def post(self, request, *args, **kwargs):
        formulario = ContatoModel2Form(request.POST)
        if formulario.is_valid():
            contato = formulario.save()
            contato.save()
            return HttpResponseRedirect(reverse_lazy("contatos:lista-contatos"))
        else:
            contexto = { 'formulario': formulario, 'mensagem': 'Erro ao salvar o contato!'}
            return render(request, "contatos/criaContato.html", contexto)
        
class ContatoUpdateView(View):
    def get(self, request, pk, *args, **kwargs):
        pessoa = Pessoa.objects.get(pk=pk)
        formulario = ContatoModel2Form(instance=pessoa)
        contexto = {'pessoa': formulario, 
                    'titulo': 'Atualiza Contato', }
        return render(request, 'contatos/atualizaContato.html', contexto)

    def post(self, request, pk, *args, **kwargs):
        pessoa = get_object_or_404(Pessoa, pk=pk)
        formulario = ContatoModel2Form(request.POST, instance=pessoa)
        if formulario.is_valid():
            pessoa = formulario.save() # atualiza uma pessoa com os dados do formulário
            pessoa.save() # salva uma pessoa no banco de dados
            return HttpResponseRedirect(reverse_lazy("contatos:lista-contatos"))
        else:
            contexto = {'pessoa': formulario, }
            return render(request, 'contatos/atualizaContato.html', contexto)

class ContatoDeleteView(View):
    def get(self, request, pk, *args, **kwargs):
        pessoa = Pessoa.objects.get(pk=pk)
        contexto = { 'pessoa': pessoa, }
        return render(request, 'contatos/apagaContato.html', contexto)
    
    def post(self, request, pk, *args, **kwargs):
        pessoa = Pessoa.objects.get(pk=pk)
        pessoa.delete()
        return HttpResponseRedirect(reverse_lazy("contatos:lista-contatos"))

raizexemplo/exemplo/contatos/templates/contatos/apagaContato.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Apaga Contato</title>
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>Remoção de contatos</h1>
    <form method="POST">
        {% csrf_token %}
        Confirma a remoção de {{ pessoa }}?<br>
        <button>
            <a href="{% url 'contatos:lista-contatos' %}"
            style="text-decoration: none; color: black;">Cancela</a>
        </button>
        <input type="submit" value="Remove">
    </form>
</body>
</html>

raizexemplo/exemplo/contatos/templates/contatos/atualizaContato.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Atualiza Contato</title>
    <link rel="stylesheet" href="{% static 'contatos/css/estilo.css' %}">
    {% include 'contatos/header.html' %}
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>{{ titulo }}</h1>
    <form method="POST" class='formulario'>
        {% csrf_token %}
        <table>
            {{ pessoa.as_table }}
                <tr>
                    <td></td>
                </tr>
        </table>
        <button type="submit" class="btn btn-primary value="Atualiza">Atualizar</button>
    </form>
</body>
</html>

raizexemplo/exemplo/contatos/templates/contatos/criaContato.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Cria Contato</title>
    <link rel="stylesheet"
    href="{% static 'contatos/css/estilo.css' %}">
    {% include 'contatos/header.html' %}
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>Cria um contato</h1>
    <form action="" method="POST">
        <fieldset style="width: max-content;">
            <legend>Formulário de Cadastro</legend>
            {% csrf_token %}
            <table class='formulario'>
                {{ formulario.as_table }}
            </table>
            {% if mensagem %}
                <p> {{ mensagem }}</p>
            {% endif %}
            <button type="submit" class="btn btn-primary">Cria contato</button>
        </fieldset>
    </form>
</body>
</html>

raizexemplo/exemplo/contatos/templates/contatos/header.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

raizexemplo/exemplo/contatos/templates/contatos/links.html
<!--
Para incluir esse fragmento de página HTML
em uma página HTML use:
{ % include 'contatos/links.html' % }
-->
<a href="/" class="btn btn-primary disabled">
Home-Page
</a> |
<a href="{% url 'contatos:home-contatos' %}" class="btn btn-primary">
Página inicial
</a> |
<a href="{% url 'contatos:lista-contatos' %}" class="btn btn-primary">
Listar contatos
</a> |
<a href="{% url 'contatos:cria-contato' %}" class="btn btn-primary">
Cadastrar contato
</a>
<hr>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

raizexemplo/exemplo/contatos/templates/contatos/listaContatos.html
{% load static %} <!--Sempre que usar statics para CSS, JS ou imagens, lembrar de colocar isso-->
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Lista Contatos</title>
    <link rel="stylesheet" href="{% static 'contatos/css/estilo.css' %}">
    {% include 'contatos/header.html' %}
</head>
<body>
    {% include 'contatos/links.html' %}
    <h1>Lista de Contatos</h1>
    <table border="2">
        <tr><th>Nome</th><th>Idade</th><th>Salário</th><th>Telefone</th><th>Ações disponíveis</th></tr>
        {% for pessoa in pessoas %} <!-- 'pessoas' vem do contexto no views.py -->
            <tr>
                <td>{{ pessoa.nome }}</td><td>{{pessoa.idade }}</td><td>{{ pessoa.salario }}</td><td>{{ pessoa.telefone }}</td>
                <td><a href="{% url 'contatos:atualiza-contato' pk=pessoa.id %}">Atualizar</a> |
                <a href="{% url 'contatos:apaga-contato' pk=pessoa.id %}">Excluir</a></td>
            </tr>
        {% empty %}
            <tr><th colspan="5">Ainda não tem contatos cadastrados</th></tr>
        {% endfor %}
    </table>
</body>
</html>